<?php

namespace Database\Seeders;

use App\Modules\AdminAuth\Models\Permission;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PermissionsSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $permissions = [
            ['name' => 'View Dashboard', 'slug' => 'dashboard.view', 'module' => 'dashboard'],
            ['name' => 'View Analytics', 'slug' => 'analytics.view', 'module' => 'analytics'],
            ['name' => 'Manage Analytics', 'slug' => 'analytics.manage', 'module' => 'analytics'],
            ['name' => 'View Reports', 'slug' => 'report.view', 'module' => 'report'],
            ['name' => 'Export Reports', 'slug' => 'report.export', 'module' => 'report'],
            ['name' => 'View Settings', 'slug' => 'settings.view', 'module' => 'settings'],
            ['name' => 'Update Settings', 'slug' => 'settings.update', 'module' => 'settings'],
            ['name' => 'View Staff', 'slug' => 'staff.view', 'module' => 'staff'],
            ['name' => 'Create Staff', 'slug' => 'staff.create', 'module' => 'staff'],
            ['name' => 'Update Staff', 'slug' => 'staff.update', 'module' => 'staff'],
            ['name' => 'View Roles', 'slug' => 'roles.view', 'module' => 'roles'],
            ['name' => 'View Audit', 'slug' => 'audit.view', 'module' => 'audit'],
            ['name' => 'View Media', 'slug' => 'media.view', 'module' => 'media'],
            ['name' => 'Upload Media', 'slug' => 'media.upload', 'module' => 'media'],
            ['name' => 'Delete Media', 'slug' => 'media.delete', 'module' => 'media'],
            ['name' => 'View Categories', 'slug' => 'category.view', 'module' => 'category'],
            ['name' => 'Create Categories', 'slug' => 'category.create', 'module' => 'category'],
            ['name' => 'Update Categories', 'slug' => 'category.update', 'module' => 'category'],
            ['name' => 'Delete Categories', 'slug' => 'category.delete', 'module' => 'category'],
            ['name' => 'View Brands', 'slug' => 'brand.view', 'module' => 'brand'],
            ['name' => 'Create Brands', 'slug' => 'brand.create', 'module' => 'brand'],
            ['name' => 'Update Brands', 'slug' => 'brand.update', 'module' => 'brand'],
            ['name' => 'Delete Brands', 'slug' => 'brand.delete', 'module' => 'brand'],
            ['name' => 'View Products', 'slug' => 'product.view', 'module' => 'product'],
            ['name' => 'Create Products', 'slug' => 'product.create', 'module' => 'product'],
            ['name' => 'Update Products', 'slug' => 'product.update', 'module' => 'product'],
            ['name' => 'Delete Products', 'slug' => 'product.delete', 'module' => 'product'],
            ['name' => 'View Purchases', 'slug' => 'purchase.view', 'module' => 'purchase'],
            ['name' => 'Create Purchases', 'slug' => 'purchase.create', 'module' => 'purchase'],
            ['name' => 'Update Purchases', 'slug' => 'purchase.update', 'module' => 'purchase'],
            ['name' => 'Delete Purchases', 'slug' => 'purchase.delete', 'module' => 'purchase'],
            ['name' => 'View Variants', 'slug' => 'variant.view', 'module' => 'variant'],
            ['name' => 'Create Variants', 'slug' => 'variant.create', 'module' => 'variant'],
            ['name' => 'Update Variants', 'slug' => 'variant.update', 'module' => 'variant'],
            ['name' => 'Delete Variants', 'slug' => 'variant.delete', 'module' => 'variant'],
            ['name' => 'View Combos', 'slug' => 'combo.view', 'module' => 'combo'],
            ['name' => 'Create Combos', 'slug' => 'combo.create', 'module' => 'combo'],
            ['name' => 'Update Combos', 'slug' => 'combo.update', 'module' => 'combo'],
            ['name' => 'Delete Combos', 'slug' => 'combo.delete', 'module' => 'combo'],
            ['name' => 'View Theme', 'slug' => 'theme.view', 'module' => 'theme'],
            ['name' => 'Update Theme', 'slug' => 'theme.update', 'module' => 'theme'],
            ['name' => 'View Storefront Theme', 'slug' => 'storefront.theme.view', 'module' => 'storefront'],
            ['name' => 'Manage Storefront Theme', 'slug' => 'storefront.theme.manage', 'module' => 'storefront'],
            ['name' => 'View Reviews', 'slug' => 'reviews.view', 'module' => 'reviews'],
            ['name' => 'Manage Reviews', 'slug' => 'reviews.manage', 'module' => 'reviews'],
            ['name' => 'View Loyalty', 'slug' => 'loyalty.view', 'module' => 'loyalty'],
            ['name' => 'View Landing Pages', 'slug' => 'landing.view', 'module' => 'landing'],
            ['name' => 'Create Landing Pages', 'slug' => 'landing.create', 'module' => 'landing'],
            ['name' => 'Update Landing Pages', 'slug' => 'landing.update', 'module' => 'landing'],
            ['name' => 'Delete Landing Pages', 'slug' => 'landing.delete', 'module' => 'landing'],
            ['name' => 'View Checkout Recoveries', 'slug' => 'recovery.view', 'module' => 'recovery'],
            ['name' => 'Update Checkout Recoveries', 'slug' => 'recovery.update', 'module' => 'recovery'],
            ['name' => 'View Orders', 'slug' => 'order.view', 'module' => 'order'],
            ['name' => 'Update Orders', 'slug' => 'order.update', 'module' => 'order'],
            ['name' => 'View Verification', 'slug' => 'verification.view', 'module' => 'verification'],
            ['name' => 'Update Verification', 'slug' => 'verification.update', 'module' => 'verification'],
            ['name' => 'View Courier', 'slug' => 'courier.view', 'module' => 'courier'],
            ['name' => 'Assign Courier', 'slug' => 'courier.assign', 'module' => 'courier'],
            ['name' => 'Update Courier', 'slug' => 'courier.update', 'module' => 'courier'],
            ['name' => 'View Courier Performance', 'slug' => 'courier.performance.view', 'module' => 'courier'],
            ['name' => 'Recalculate Courier Performance', 'slug' => 'courier.performance.recalculate', 'module' => 'courier'],
            ['name' => 'View Finance', 'slug' => 'finance.view', 'module' => 'finance'],
            ['name' => 'Manage Finance', 'slug' => 'finance.manage', 'module' => 'finance'],
            ['name' => 'View Marketing', 'slug' => 'marketing.view', 'module' => 'marketing'],
            ['name' => 'Update Marketing', 'slug' => 'marketing.update', 'module' => 'marketing'],
            ['name' => 'View Marketing Command Center', 'slug' => 'marketing.command.view', 'module' => 'marketing'],
            ['name' => 'Manage Marketing Command Center', 'slug' => 'marketing.command.manage', 'module' => 'marketing'],
            ['name' => 'View Marketing Segments', 'slug' => 'marketing.segment.view', 'module' => 'marketing'],
            ['name' => 'Manage Marketing Segments', 'slug' => 'marketing.segment.manage', 'module' => 'marketing'],
            ['name' => 'Recalculate Marketing Segments', 'slug' => 'marketing.segment.recalculate', 'module' => 'marketing'],
            ['name' => 'View Marketing Campaigns', 'slug' => 'marketing.campaign.view', 'module' => 'marketing'],
            ['name' => 'Manage Marketing Campaigns', 'slug' => 'marketing.campaign.manage', 'module' => 'marketing'],
            ['name' => 'Queue Marketing Campaigns', 'slug' => 'marketing.campaign.queue', 'module' => 'marketing'],
            ['name' => 'View Expenses', 'slug' => 'expense.view', 'module' => 'expense'],
            ['name' => 'Create Expenses', 'slug' => 'expense.create', 'module' => 'expense'],
            ['name' => 'Update Expenses', 'slug' => 'expense.update', 'module' => 'expense'],
            ['name' => 'Delete Expenses', 'slug' => 'expense.delete', 'module' => 'expense'],
            ['name' => 'View Promotions', 'slug' => 'promotion.view', 'module' => 'promotion'],
            ['name' => 'Create Promotions', 'slug' => 'promotion.create', 'module' => 'promotion'],
            ['name' => 'Update Promotions', 'slug' => 'promotion.update', 'module' => 'promotion'],
            ['name' => 'Delete Promotions', 'slug' => 'promotion.delete', 'module' => 'promotion'],
            ['name' => 'View Facebook Tracking', 'slug' => 'facebook.view', 'module' => 'facebook'],
            ['name' => 'Update Facebook Tracking', 'slug' => 'facebook.update', 'module' => 'facebook'],
            ['name' => 'View Security', 'slug' => 'security.view', 'module' => 'security'],
            ['name' => 'View System Diagnostics', 'slug' => 'system.diagnostics.view', 'module' => 'system'],
            ['name' => 'Manage System Diagnostics', 'slug' => 'system.diagnostics.manage', 'module' => 'system'],
            ['name' => 'View Backups', 'slug' => 'backup.view', 'module' => 'backup'],
            ['name' => 'Create Backups', 'slug' => 'backup.create', 'module' => 'backup'],
            ['name' => 'Validate Backups', 'slug' => 'backup.validate', 'module' => 'backup'],
            ['name' => 'View Deployment', 'slug' => 'deployment.view', 'module' => 'deployment'],
            ['name' => 'View RTO Risk', 'slug' => 'risk.view', 'module' => 'risk'],
            ['name' => 'Recalculate RTO Risk', 'slug' => 'risk.recalculate', 'module' => 'risk'],
            ['name' => 'View RTO Holds', 'slug' => 'risk.hold.view', 'module' => 'risk'],
            ['name' => 'Release RTO Holds', 'slug' => 'risk.hold.release', 'module' => 'risk'],
            ['name' => 'View Tracking', 'slug' => 'tracking.view', 'module' => 'tracking'],
            ['name' => 'Update Tracking', 'slug' => 'tracking.update', 'module' => 'tracking'],
            ['name' => 'View Customers', 'slug' => 'customer.view', 'module' => 'customer'],
            ['name' => 'View Customer Intelligence', 'slug' => 'customer.intelligence.view', 'module' => 'customer'],
            ['name' => 'View Customer Segments', 'slug' => 'customer.segment.view', 'module' => 'customer'],
            ['name' => 'Recalculate Customer Segments', 'slug' => 'customer.segment.recalculate', 'module' => 'customer'],
            ['name' => 'View Customer Follow-ups', 'slug' => 'customer.followup.view', 'module' => 'customer'],
            ['name' => 'View Customer Retention', 'slug' => 'customer.retention.view', 'module' => 'customer'],
            ['name' => 'View Customer Lifecycle', 'slug' => 'customer.lifecycle.view', 'module' => 'customer'],
            ['name' => 'View Customer Fraud', 'slug' => 'customer.fraud.view', 'module' => 'customer'],
            ['name' => 'Manage Customer Blacklist', 'slug' => 'customer.blacklist.manage', 'module' => 'customer'],
            ['name' => 'View Communications', 'slug' => 'communication.view', 'module' => 'communication'],
            ['name' => 'Manage Communications', 'slug' => 'communication.manage', 'module' => 'communication'],
            ['name' => 'Create Communications', 'slug' => 'communication.create', 'module' => 'communication'],
            ['name' => 'View Automations', 'slug' => 'automation.view', 'module' => 'automation'],
            ['name' => 'Manage Automations', 'slug' => 'automation.manage', 'module' => 'automation'],
            ['name' => 'Run Automations', 'slug' => 'automation.run', 'module' => 'automation'],
        ];

        foreach ($permissions as $permission) {
            Permission::updateOrCreate(['slug' => $permission['slug']], $permission);
        }
    }
}
