<?php

namespace Database\Seeders;

use App\Modules\AdminAuth\Models\Permission;
use App\Modules\AdminAuth\Models\Role;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RolesPermissionSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $ownerPermissions = [
            'dashboard.view',
            'analytics.view',
            'analytics.manage',
            'report.view',
            'report.export',
            'settings.view',
            'settings.update',
            'staff.view',
            'staff.create',
            'staff.update',
            'roles.view',
            'audit.view',
            'media.view',
            'media.upload',
            'media.delete',
            'category.view',
            'category.create',
            'category.update',
            'category.delete',
            'brand.view',
            'brand.create',
            'brand.update',
            'brand.delete',
            'product.view',
            'product.create',
            'product.update',
            'product.delete',
            'purchase.view',
            'purchase.create',
            'purchase.update',
            'purchase.delete',
            'variant.view',
            'variant.create',
            'variant.update',
            'variant.delete',
            'combo.view',
            'combo.create',
            'combo.update',
            'combo.delete',
            'theme.view',
            'theme.update',
            'storefront.theme.view',
            'storefront.theme.manage',
            'reviews.view',
            'reviews.manage',
            'loyalty.view',
            'landing.view',
            'landing.create',
            'landing.update',
            'landing.delete',
            'recovery.view',
            'recovery.update',
            'order.view',
            'order.update',
            'verification.view',
            'verification.update',
            'courier.view',
            'courier.assign',
            'courier.update',
            'courier.performance.view',
            'courier.performance.recalculate',
            'finance.view',
            'finance.manage',
            'marketing.view',
            'marketing.update',
            'marketing.command.view',
            'marketing.command.manage',
            'marketing.segment.view',
            'marketing.segment.manage',
            'marketing.segment.recalculate',
            'marketing.campaign.view',
            'marketing.campaign.manage',
            'marketing.campaign.queue',
            'expense.view',
            'expense.create',
            'expense.update',
            'expense.delete',
            'promotion.view',
            'promotion.create',
            'promotion.update',
            'promotion.delete',
            'facebook.view',
            'facebook.update',
            'security.view',
            'system.diagnostics.view',
            'system.diagnostics.manage',
            'backup.view',
            'backup.create',
            'backup.validate',
            'deployment.view',
            'risk.view',
            'risk.recalculate',
            'risk.hold.view',
            'risk.hold.release',
            'tracking.view',
            'tracking.update',
            'customer.view',
            'customer.intelligence.view',
            'customer.segment.view',
            'customer.segment.recalculate',
            'customer.followup.view',
            'customer.retention.view',
            'customer.lifecycle.view',
            'customer.fraud.view',
            'customer.blacklist.manage',
            'communication.view',
            'communication.manage',
            'communication.create',
            'automation.view',
            'automation.manage',
            'automation.run',
        ];

        $managerPermissions = [
            'dashboard.view',
            'analytics.view',
            'analytics.manage',
            'report.view',
            'report.export',
            'settings.view',
            'staff.view',
            'audit.view',
            'media.view',
            'media.upload',
            'category.view',
            'category.create',
            'category.update',
            'brand.view',
            'brand.create',
            'brand.update',
            'product.view',
            'product.create',
            'product.update',
            'purchase.view',
            'purchase.create',
            'purchase.update',
            'variant.view',
            'variant.create',
            'variant.update',
            'combo.view',
            'combo.create',
            'combo.update',
            'theme.view',
            'storefront.theme.view',
            'storefront.theme.manage',
            'reviews.view',
            'reviews.manage',
            'loyalty.view',
            'landing.view',
            'landing.create',
            'landing.update',
            'recovery.view',
            'recovery.update',
            'order.view',
            'order.update',
            'verification.view',
            'verification.update',
            'courier.view',
            'courier.assign',
            'courier.update',
            'courier.performance.view',
            'finance.view',
            'finance.manage',
            'marketing.view',
            'marketing.update',
            'marketing.command.view',
            'marketing.command.manage',
            'marketing.segment.view',
            'marketing.segment.manage',
            'marketing.segment.recalculate',
            'marketing.campaign.view',
            'marketing.campaign.manage',
            'marketing.campaign.queue',
            'expense.view',
            'expense.create',
            'expense.update',
            'promotion.view',
            'promotion.create',
            'promotion.update',
            'facebook.view',
            'security.view',
            'system.diagnostics.view',
            'backup.view',
            'backup.create',
            'backup.validate',
            'deployment.view',
            'risk.view',
            'risk.hold.view',
            'risk.hold.release',
            'tracking.view',
            'tracking.update',
            'customer.view',
            'customer.intelligence.view',
            'customer.segment.view',
            'customer.followup.view',
            'customer.retention.view',
            'customer.lifecycle.view',
            'customer.fraud.view',
            'customer.blacklist.manage',
            'communication.view',
            'communication.manage',
            'communication.create',
            'automation.view',
            'automation.manage',
            'automation.run',
        ];

        $staffPermissions = [
            'dashboard.view',
            'analytics.view',
            'report.view',
            'marketing.command.view',
            'marketing.segment.view',
            'marketing.campaign.view',
            'automation.view',
            'reviews.view',
            'loyalty.view',
        ];

        // Assign permissions to owner role
        $ownerRole = Role::where('slug', 'owner')->first();
        if ($ownerRole) {
            $permissionIds = Permission::whereIn('slug', $ownerPermissions)->pluck('id')->toArray();
            $ownerRole->permissions()->sync($permissionIds);
        }

        // Assign permissions to manager role
        $managerRole = Role::where('slug', 'manager')->first();
        if ($managerRole) {
            $permissionIds = Permission::whereIn('slug', $managerPermissions)->pluck('id')->toArray();
            $managerRole->permissions()->sync($permissionIds);
        }

        // Assign permissions to staff role
        $staffRole = Role::where('slug', 'staff')->first();
        if ($staffRole) {
            $permissionIds = Permission::whereIn('slug', $staffPermissions)->pluck('id')->toArray();
            $staffRole->permissions()->sync($permissionIds);
        }
    }
}
